
name: CI
on: [push]

jobs:
  debug_xcode11_6:
    name: Debug-Xcode-11.6
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane build_debug

  release_xcode11_6:
    name: Release-Xcode-11.6
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane build_release

  debug_xcode11_7:
    name: Debug-Xcode-11.7
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane build_debug

  release_xcode11_7:
    name: Release-Xcode-11.7
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane build_release

  debug_xcode12_0:
    name: Debug-Xcode-12.0
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane build_debug

  release_xcode12_0:
    name: Release-Xcode-12.0
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane build_release
